apiVersion: v1
kind: Pod
metadata:
  name: trt-compiler-interactive
  namespace: torchrt
spec:
  restartPolicy: Never
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
  volumes:
  - name: workspace
    emptyDir: {}
  initContainers:
  - name: git-clone
    image: alpine/git:v2.43.0
    args:
      - clone
      - --
      - https://github.com/wbe7/torchrt.git
      - /workspace
    volumeMounts:
      - name: workspace
        mountPath: /workspace
  containers:
  - name: trtexec
    image: nvcr.io/nvidia/tensorrt:24.05-py3
    command: ["/bin/sh", "-c"]
    args: ["sleep infinity"]
    workingDir: /workspace
    resources:
      requests:
        memory: "8Gi"
      limits:
        memory: "16Gi"
        nvidia.com/gpu: 1
    volumeMounts:
      - name: workspace
        mountPath: /workspace
